#!/usr/bin/env python3
"""
Export curated branching comparison rows to LaTeX for the HEP decay paper.

Run from repository root:
  PYTHONPATH=scripts python3 scripts/hqiv_hep_decay_benchmark.py \\
    --json-out data/hep_decay_benchmark.json
  PYTHONPATH=scripts python3 scripts/export_hep_branching_table.py \\
    --json-in data/hep_decay_benchmark.json \\
    --tex-out papers/hep_decay_readout/generated/branching_comparison.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _repo_root() -> Path:
    """Locate the HQIV repo root from either the repo or paper subtree."""
    for parent in Path(__file__).resolve().parents:
        if (parent / "lakefile.toml").exists() and (parent / "data").is_dir():
            return parent
    return Path(__file__).resolve().parents[1]


ROOT = _repo_root()
DEFAULT_JSON = ROOT / "data" / "hep_decay_benchmark.json"
DEFAULT_TEX = ROOT / "papers/hep_decay_readout/generated/branching_comparison.tex"
DEFAULT_SUMMARY_TEX = ROOT / "papers/hep_decay_readout/generated/readout_error_distribution.tex"
DEFAULT_SPECTRUM_TEX = ROOT / "papers/hep_decay_readout/generated/sigma_spectrum.tex"


def fmt_br(x: float | None) -> str:
    if x is None:
        return "---"
    if x >= 0.01:
        return f"{100.0 * x:.2f}\\%"
    return f"{100.0 * x:.3f}\\%"


def fmt_sigma(x: float | None) -> str:
    if x is None:
        return "---"
    if x >= 0.01:
        return f"{100.0 * x:.2f}\\%"
    if x >= 0.001:
        return f"{100.0 * x:.3f}\\%"
    return f"{100.0 * x:.4f}\\%"


def fmt_ns(x: float | None) -> str:
    if x is None:
        return "---"
    if x >= 100:
        return f"{x:.0f}"
    if x >= 10:
        return f"{x:.1f}"
    return f"{x:.2f}"


PANEL_LABELS = {
    "mass": "Mass panel",
    "decay": "Decay channels",
    "branching": "Branching (new states)",
    "branching_comparison": "Curated diagnostics",
    "readout": "Open-channel readout (refs)",
    "half_life": "Half-life (width $\\sigma$)",
}


def build_spectrum_tex(summary: dict) -> str:
    spectrum = summary.get("spectrum_n_sigma") or {}
    by_panel = spectrum.get("by_panel") or {}
    combined = spectrum.get("combined") or {}
    sorted_cases = spectrum.get("sorted_cases") or []

    lines = [
        "% Auto-generated by scripts/export_hep_branching_table.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{Monte Carlo $n_\\sigma$ across the HQIV calculation spectrum.",
        " Rows count witness cases with propagated $\\sigma_{\\mathrm{pred}}$ and",
        " quarantined $\\sigma_{\\mathrm{ref}}$ where available.",
        " Combined excludes half-life (pass criterion is log$_{10}$ envelope; width-derived",
        " $\\sigma$ is not comparable to the branching/mass panels).}",
        "\\label{tab:sigma-spectrum}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrrrr@{}}",
        "\\toprule",
        "Panel & $n$ & $\\le1\\sigma$ & $\\le2\\sigma$ & $\\le3\\sigma$ & "
        "mean $n_\\sigma$ & \\textbf{median $n_\\sigma$} & max $n_\\sigma$ \\\\",
        "\\midrule",
    ]

    panel_order = (
        "mass",
        "decay",
        "branching",
        "branching_comparison",
        "readout",
        "half_life",
    )
    for panel in panel_order:
        row = by_panel.get(panel)
        if not row:
            continue
        label = PANEL_LABELS.get(panel, panel.replace("_", "\\_"))
        n = int(row.get("reference_matched_count") or 0)
        lines.append(
            f"{label} & {n} & "
            f"{int(row.get('within_1sigma') or 0)} ({fmt_fraction_pct(row.get('within_1sigma_fraction'))}) & "
            f"{int(row.get('within_2sigma') or 0)} ({fmt_fraction_pct(row.get('within_2sigma_fraction'))}) & "
            f"{int(row.get('within_3sigma') or 0)} ({fmt_fraction_pct(row.get('within_3sigma_fraction'))}) & "
            f"{fmt_ns(row.get('mean_n_sigma'))} & {fmt_ns(row.get('median_n_sigma'))} & "
            f"{fmt_ns(row.get('max_n_sigma'))} \\\\"
        )

    if combined.get("reference_matched_count"):
        lines.append("\\midrule")
        n = int(combined.get("reference_matched_count") or 0)
        lines.append(
            f"\\textbf{{Combined spectrum}} & {n} & "
            f"{int(combined.get('within_1sigma') or 0)} ({fmt_fraction_pct(combined.get('within_1sigma_fraction'))}) & "
            f"{int(combined.get('within_2sigma') or 0)} ({fmt_fraction_pct(combined.get('within_2sigma_fraction'))}) & "
            f"{int(combined.get('within_3sigma') or 0)} ({fmt_fraction_pct(combined.get('within_3sigma_fraction'))}) & "
            f"{fmt_ns(combined.get('mean_n_sigma'))} & "
            f"\\textbf{{{fmt_ns(combined.get('median_n_sigma'))}}} & "
            f"{fmt_ns(combined.get('max_n_sigma'))} \\\\"
        )

    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
            "\\begin{table}[ht]",
            "\\centering",
            "\\caption{Sorted $n_\\sigma$ deviations (largest first) over mass and",
            " branching witnesses (half-life rows omitted; see Table~\\ref{tab:sigma-spectrum}).",
            " Tiny reference $\\mathcal{B}$ rows can dominate $n_\\sigma$ even when absolute",
            " predictions are sensible.}",
            "\\label{tab:sigma-spectrum-sorted}",
            "\\footnotesize",
            "\\begin{tabular}{@{}lllr@{}}",
            "\\toprule",
            "Panel & Case & Quantity & $n_\\sigma$ \\\\",
            "\\midrule",
        ]
    )

    shown = 0
    for case in sorted_cases:
        if case.get("panel") not in (
            "mass",
            "decay",
            "branching",
            "branching_comparison",
            "readout",
        ):
            continue
        if shown >= 15:
            break
        panel = PANEL_LABELS.get(case.get("panel", ""), str(case.get("panel", "")).replace("_", "\\_"))
        case_id = str(case.get("case_id", "")).replace("_", "\\_")
        qty = str(case.get("quantity", "")).replace("_", "\\_")
        lines.append(
            f"{panel} & {case_id} & {qty} & {fmt_ns(float(case.get('n_sigma') or 0))} \\\\"
        )
        shown += 1

    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def fmt_pct_value(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{x:.1f}\\%"


def fmt_fraction_pct(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{100.0 * x:.1f}\\%"


def label_from_notes(notes: str) -> str:
    if "; n_σ=" in notes:
        return notes.split("; n_σ=")[0].strip()
    return notes.strip()


def label_for_tex(notes: str) -> str:
    label = label_from_notes(notes)
    if label.startswith("$"):
        return label
    return label.replace("_", "\\_")


def build_tex(rows: list[dict]) -> str:
    lines = [
        "% Auto-generated by scripts/export_hep_branching_table.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{HQIV branching readout vs.\\ PDG comparison targets \\cite{pdg2024}.",
        " $\\mathcal{B}_{\\mathrm{pred}}$ comes from the Lean-aligned calculator;",
        " $\\sigma_{\\mathrm{pred}}$ from Monte Carlo witness propagation;",
        " $\\sigma_{\\mathrm{ref}}$ from PDG (comparison only).}",
        "\\label{tab:branching-comparison}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrr@{}}",
        "\\toprule",
        "Channel & $\\mathcal{B}_{\\mathrm{ref}}$ & $\\mathcal{B}_{\\mathrm{pred}}$ & "
        "$\\sigma_{\\mathrm{ref}}$ & $\\sigma_{\\mathrm{pred}}$ & $n_\\sigma$ \\\\",
        "\\midrule",
    ]
    for row in rows:
        label_tex = label_for_tex(str(row.get("notes", row.get("case_id", ""))))
        ref = row.get("reference")
        pred = row.get("predicted")
        ref_s = row.get("reference_sigma")
        pred_s = row.get("predicted_sigma")
        n_sig = row.get("n_sigma")
        lines.append(
            f"{label_tex} & {fmt_br(ref)} & {fmt_br(pred)} & "
            f"{fmt_sigma(ref_s)} & {fmt_sigma(pred_s)} & {fmt_ns(n_sig)} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def build_error_distribution_tex(summary: dict) -> str:
    readout = summary.get("readout_n_sigma_distribution") or {}
    diagnostic = summary.get("diagnostic_branching_n_sigma_distribution") or {}
    lines = [
        "% Auto-generated by scripts/export_hep_branching_table.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{Monte Carlo $n_\\sigma$ distribution for HQIV branching readouts.",
        " Open rows count the full export panel; ref.\\ rows count channels with",
        " propagated $\\sigma_{\\mathrm{pred}}$ and quarantined $\\sigma_{\\mathrm{ref}}$.",
        " The broad readout panel has few PDG rows with complete uncertainty metadata;",
        " the curated $17$-channel diagnostic panel is the primary $\\sigma$ scorecard.}",
        "\\label{tab:readout-error-distribution}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrrrr@{}}",
        "\\toprule",
        "Panel & open & ref. & $\\le1\\sigma$ & $\\le2\\sigma$ & $\\le3\\sigma$ & "
        "mean $n_\\sigma$ & max $n_\\sigma$ \\\\",
        "\\midrule",
    ]
    for label, row in (
        ("Full readout", readout),
        ("Curated diagnostics", diagnostic),
    ):
        w1 = row.get("within_1sigma")
        w2 = row.get("within_2sigma")
        w3 = row.get("within_3sigma")
        ref_n = int(row.get("reference_matched_count") or 0)
        lines.append(
            f"{label} & {int(row.get('open_channel_count') or 0)} & {ref_n} & "
            f"{int(w1 or 0)} ({fmt_fraction_pct(row.get('within_1sigma_fraction'))}) & "
            f"{int(w2 or 0)} ({fmt_fraction_pct(row.get('within_2sigma_fraction'))}) & "
            f"{int(w3 or 0)} ({fmt_fraction_pct(row.get('within_3sigma_fraction'))}) & "
            f"{fmt_ns(row.get('mean_n_sigma'))} & {fmt_ns(row.get('max_n_sigma'))} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Export HEP branching comparison LaTeX table")
    parser.add_argument("--json-in", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--tex-out", type=Path, default=DEFAULT_TEX)
    parser.add_argument("--summary-tex-out", type=Path, default=DEFAULT_SUMMARY_TEX)
    parser.add_argument("--spectrum-tex-out", type=Path, default=DEFAULT_SPECTRUM_TEX)
    args = parser.parse_args()

    payload = json.loads(args.json_in.read_text(encoding="utf-8"))
    rows = [
        r
        for r in payload.get("rows", [])
        if r.get("panel") == "branching_comparison" and r.get("predicted") is not None
    ]
    if len(rows) < 10:
        raise SystemExit(f"expected at least 10 branching_comparison rows, got {len(rows)}")

    tex = build_tex(rows)
    args.tex_out.parent.mkdir(parents=True, exist_ok=True)
    args.tex_out.write_text(tex, encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {args.tex_out}")
    summary_tex = build_error_distribution_tex(payload.get("summary") or {})
    args.summary_tex_out.parent.mkdir(parents=True, exist_ok=True)
    args.summary_tex_out.write_text(summary_tex, encoding="utf-8")
    print(f"Wrote readout summary to {args.summary_tex_out}")
    spectrum_tex = build_spectrum_tex(payload.get("summary") or {})
    args.spectrum_tex_out.parent.mkdir(parents=True, exist_ok=True)
    args.spectrum_tex_out.write_text(spectrum_tex, encoding="utf-8")
    print(f"Wrote sigma spectrum to {args.spectrum_tex_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
