#!/usr/bin/env python3
"""
Export curated branching comparison rows to LaTeX for the HEP decay paper.

Run from repository root:
  PYTHONPATH=scripts python3 scripts/hqiv_hep_decay_benchmark.py \\
    --json-out data/hep_decay_benchmark.json
  PYTHONPATH=scripts python3 scripts/export_hep_branching_table.py \\
    --json-in data/hep_decay_benchmark.json \\
    --tex-out papers/hep_decay_readout/generated/branching_comparison.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _repo_root() -> Path:
    """Locate the HQIV repo root from either the repo or paper subtree."""
    for parent in Path(__file__).resolve().parents:
        if (parent / "lakefile.toml").exists() and (parent / "data").is_dir():
            return parent
    return Path(__file__).resolve().parents[1]


ROOT = _repo_root()
DEFAULT_JSON = ROOT / "data" / "hep_decay_benchmark.json"
DEFAULT_TEX = ROOT / "papers/hep_decay_readout/generated/branching_comparison.tex"
DEFAULT_SUMMARY_TEX = ROOT / "papers/hep_decay_readout/generated/readout_error_distribution.tex"


def fmt_br(x: float | None) -> str:
    if x is None:
        return "---"
    if x >= 0.01:
        return f"{100.0 * x:.2f}\\%"
    return f"{100.0 * x:.3f}\\%"


def fmt_sigma(x: float | None) -> str:
    if x is None:
        return "---"
    if x >= 0.01:
        return f"{100.0 * x:.2f}\\%"
    if x >= 0.001:
        return f"{100.0 * x:.3f}\\%"
    return f"{100.0 * x:.4f}\\%"


def fmt_ns(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{x:.2f}"


def fmt_pct_value(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{x:.1f}\\%"


def fmt_fraction_pct(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{100.0 * x:.1f}\\%"


def label_from_notes(notes: str) -> str:
    if "; n_σ=" in notes:
        return notes.split("; n_σ=")[0].strip()
    return notes.strip()


def label_for_tex(notes: str) -> str:
    label = label_from_notes(notes)
    if label.startswith("$"):
        return label
    return label.replace("_", "\\_")


def build_tex(rows: list[dict]) -> str:
    lines = [
        "% Auto-generated by scripts/export_hep_branching_table.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{HQIV branching readout vs.\\ PDG comparison targets \\cite{pdg2024}.",
        " $\\mathcal{B}_{\\mathrm{pred}}$ comes from the Lean-aligned calculator;",
        " $\\sigma_{\\mathrm{pred}}$ from Monte Carlo witness propagation;",
        " $\\sigma_{\\mathrm{ref}}$ from PDG (comparison only).}",
        "\\label{tab:branching-comparison}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrr@{}}",
        "\\toprule",
        "Channel & $\\mathcal{B}_{\\mathrm{ref}}$ & $\\mathcal{B}_{\\mathrm{pred}}$ & "
        "$\\sigma_{\\mathrm{ref}}$ & $\\sigma_{\\mathrm{pred}}$ & $n_\\sigma$ \\\\",
        "\\midrule",
    ]
    for row in rows:
        label_tex = label_for_tex(str(row.get("notes", row.get("case_id", ""))))
        ref = row.get("reference")
        pred = row.get("predicted")
        ref_s = row.get("reference_sigma")
        pred_s = row.get("predicted_sigma")
        n_sig = row.get("n_sigma")
        lines.append(
            f"{label_tex} & {fmt_br(ref)} & {fmt_br(pred)} & "
            f"{fmt_sigma(ref_s)} & {fmt_sigma(pred_s)} & {fmt_ns(n_sig)} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def build_error_distribution_tex(summary: dict) -> str:
    readout = summary.get("readout_error_distribution") or {}
    diagnostic = summary.get("diagnostic_branching_error_distribution") or {}
    lines = [
        "% Auto-generated by scripts/export_hep_branching_table.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{Relative-error distribution for HQIV branching readouts.",
        " The readout count is the full open-channel export; percentages are",
        " computed only on rows with direct PDG branching references in the comparison layer.}",
        "\\label{tab:readout-error-distribution}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrrr@{}}",
        "\\toprule",
        "Panel & open rows & ref. rows & $\\le10\\%$ & $\\le20\\%$ & mean $|\\Delta|$ & max $|\\Delta|$ \\\\",
        "\\midrule",
    ]
    for label, row in (
        ("Full readout", readout),
        ("Curated diagnostics", diagnostic),
    ):
        lines.append(
            f"{label} & {int(row.get('open_channel_count') or 0)} & "
            f"{int(row.get('reference_matched_count') or 0)} & "
            f"{int(row.get('within_10pct') or 0)} ({fmt_fraction_pct(row.get('within_10pct_fraction'))}) & "
            f"{int(row.get('within_20pct') or 0)} ({fmt_fraction_pct(row.get('within_20pct_fraction'))}) & "
            f"{fmt_pct_value(row.get('mean_abs_error_pct'))} & "
            f"{fmt_pct_value(row.get('max_abs_error_pct'))} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Export HEP branching comparison LaTeX table")
    parser.add_argument("--json-in", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--tex-out", type=Path, default=DEFAULT_TEX)
    parser.add_argument("--summary-tex-out", type=Path, default=DEFAULT_SUMMARY_TEX)
    args = parser.parse_args()

    payload = json.loads(args.json_in.read_text(encoding="utf-8"))
    rows = [
        r
        for r in payload.get("rows", [])
        if r.get("panel") == "branching_comparison" and r.get("predicted") is not None
    ]
    if len(rows) < 10:
        raise SystemExit(f"expected at least 10 branching_comparison rows, got {len(rows)}")

    tex = build_tex(rows)
    args.tex_out.parent.mkdir(parents=True, exist_ok=True)
    args.tex_out.write_text(tex, encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {args.tex_out}")
    summary_tex = build_error_distribution_tex(payload.get("summary") or {})
    args.summary_tex_out.parent.mkdir(parents=True, exist_ok=True)
    args.summary_tex_out.write_text(summary_tex, encoding="utf-8")
    print(f"Wrote readout summary to {args.summary_tex_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
