#!/usr/bin/env python3
"""
Export Lean-aligned electroweak mass observation rows to LaTeX for the HEP paper.

Run from repository root:
  PYTHONPATH=scripts python3 scripts/hqiv_electroweak_mass_benchmark.py \\
    --json-out data/electroweak_mass_benchmark.json
  PYTHONPATH=scripts python3 scripts/export_electroweak_mass_table.py \\
    --json-in data/electroweak_mass_benchmark.json \\
    --tex-out papers/hep_decay_readout/generated/electroweak_mass_observation.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "lakefile.toml").exists() and (parent / "data").is_dir():
            return parent
    return Path(__file__).resolve().parents[1]


ROOT = _repo_root()
DEFAULT_JSON = ROOT / "data" / "electroweak_mass_benchmark.json"
DEFAULT_TEX = ROOT / "papers/hep_decay_readout/generated/electroweak_mass_observation.tex"

FACILITY_LABELS = {
    "lep_line_shape": "LEP line-shape",
    "cdf_tevatron": "CDF Tevatron",
    "d0_tevatron": "D0 Tevatron",
    "cms_lhc": "CMS LHC",
    "atlas_lhc": "ATLAS LHC",
}


def fmt_mev(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{x:,.1f}"


def fmt_ns(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{x:.2f}"


def export_tex(payload: dict) -> str:
    cert = payload.get("certificate") or {}
    pole = float(cert.get("pole_mw_mev", 0.0))
    ledger = {row["facility_id"]: row for row in payload.get("facility_ledger") or []}
    cases = {row["case_id"]: row for row in payload.get("cases") or []}

    lines = [
        "% Auto-generated by scripts/export_electroweak_mass_table.py",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{Electroweak mass observation chart (diagnostic comparison). "
        "Pole and facility rows follow \\texttt{ElectroweakMassObservation.lean}; "
        "reference $m_W$ values are quarantined comparison numerals.}",
        "\\label{tab:ew-mass-observation}",
        "\\small",
        "\\begin{tabular}{@{}llrrrr@{}}",
        "\\toprule",
        "Facility & Chart & $f_{\\mathrm{dress}}$ & $m_W^{\\mathrm{HQIV}}$ (MeV) & "
        "$m_W^{\\mathrm{ref}}$ (MeV) & $n_\\sigma$ \\\\",
        "\\midrule",
        f"Pole (TUFT) & --- & 1 & {fmt_mev(pole)} & --- & --- \\\\",
    ]

    obs_order = [
        ("lep_combined_w", "lep_line_shape"),
        ("d0_w_mass", "d0_tevatron"),
        ("cms_w_mass_2024", "cms_lhc"),
        ("cdf_w_mass_2022", "cdf_tevatron"),
    ]
    for obs_id, fac_id in obs_order:
        case = cases.get(obs_id, {})
        fac = ledger.get(fac_id, {})
        label = FACILITY_LABELS.get(fac_id, fac_id.replace("_", "\\_"))
        chart = str(fac.get("dressing_chart", "---")).replace("_", "\\_")
        f_dress = fac.get("facility_mass_dressing_factor")
        pred = case.get("predicted")
        ref = case.get("reference")
        ns = case.get("n_sigma")
        f_txt = f"{float(f_dress):.6f}" if f_dress is not None else "---"
        lines.append(
            f"{label} & {chart} & {f_txt} & {fmt_mev(float(pred)) if pred is not None else '---'} & "
            f"{fmt_mev(float(ref)) if ref is not None else '---'} & {fmt_ns(ns)} \\\\"
        )

    atlas = ledger.get("atlas_lhc")
    if atlas:
        atlas_f = atlas.get("facility_mass_dressing_factor")
        atlas_f_txt = f"{float(atlas_f):.6f}" if atlas_f is not None else "---"
        lines.append(
            f"ATLAS LHC & collider\\_native & {atlas_f_txt} & "
            f"{fmt_mev(float(atlas.get('apparent_mw_mev')))} & --- & --- \\\\"
        )

    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


# Pipeline alias (``hqiv_hep_readout_pipeline.py``)
build_tex = export_tex


def main() -> None:
    parser = argparse.ArgumentParser(description="Export electroweak mass LaTeX table")
    parser.add_argument("--json-in", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--tex-out", type=Path, default=DEFAULT_TEX)
    args = parser.parse_args()

    payload = json.loads(args.json_in.read_text(encoding="utf-8"))
    tex = export_tex(payload)
    args.tex_out.parent.mkdir(parents=True, exist_ok=True)
    args.tex_out.write_text(tex, encoding="utf-8")
    print(f"Wrote {args.tex_out}")


if __name__ == "__main__":
    main()
