#!/usr/bin/env python3
"""
Export σ-floor sensitivity, CKM slot comparison, and branching diagnostic figures
for the HEP decay readout paper (peer-review revision package).

Run from repository root:
  PYTHONPATH=scripts python3 scripts/export_sigma_audit_tex.py
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import hqiv_hep_decay_chain as hep
import hqiv_lean_physics_primitives as lean


def _repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "lakefile.toml").exists() and (parent / "data").is_dir():
            return parent
    return Path(__file__).resolve().parents[1]


ROOT = _repo_root()
DEFAULT_EXCITED_JSON = ROOT / "data" / "excited_mass_comparison.json"
DEFAULT_BENCHMARK_JSON = ROOT / "data" / "hep_decay_benchmark.json"
DEFAULT_OBSERVATIONS_JSON = ROOT / "data" / "hep_decay_observations.json"
GENERATED = ROOT / "papers/hep_decay_readout/generated"

GAMMA = 2.0 / 5.0
CKM_SLOTS = (
    ("V_{us}", math.sqrt(GAMMA / 8.0), 0.2243, 0.0005),
    ("V_{cd}", math.sqrt(GAMMA / 16.0), 0.221, 0.004),
    ("V_{cb}", math.sqrt(GAMMA / 32.0), 0.0408, 0.0014),
)

MASS_FLOORS = (0.005, 0.01, 0.02)
LEDGER_LABELS = {
    "strong": "II (strong/OZI)",
    "weak": "III (weak)",
    "em": "II/EM",
}


def fmt_br(x: float | None) -> str:
    if x is None:
        return "---"
    if x >= 0.01:
        return f"{100.0 * x:.2f}\\%"
    return f"{100.0 * x:.3f}\\%"


def fmt_sigma(x: float | None) -> str:
    if x is None:
        return "---"
    if x >= 0.01:
        return f"{100.0 * x:.2f}\\%"
    if x >= 0.001:
        return f"{100.0 * x:.3f}\\%"
    return f"{100.0 * x:.4f}\\%"


def fmt_ns(x: float | None) -> str:
    if x is None:
        return "---"
    if x >= 100:
        return f"{x:.0f}"
    if x >= 10:
        return f"{x:.1f}"
    return f"{x:.2f}"


def fmt_qm(x: float | None) -> str:
    if x is None:
        return "---"
    return f"{x:.3f}"


def fmt_fraction_pct(x: float) -> str:
    return f"{100.0 * x:.0f}\\%"


def _latex_sanitize(text: str) -> str:
    replacements = {
        "π": "$\\pi$",
        "ρ": "$\\rho$",
        "ω": "$\\omega$",
        "η": "$\\eta$",
        "→": "$\\to$",
        "±": "$\\pm$",
    }
    out = text
    for src, dst in replacements.items():
        out = out.replace(src, dst)
    return out.replace("_", "\\_").replace("%", "\\%")


def _mass_floor_metrics(rows: list[dict], floor_frac: float) -> dict[str, Any]:
    listed_ns: list[float] = []
    floored_ns: list[float] = []
    for row in rows:
        pdg = row.get("pdg_mev")
        sigma = row.get("sigma_mev")
        delta = row.get("delta_mev")
        if pdg is None or sigma is None or sigma <= 0 or delta is None:
            continue
        ad = abs(float(delta))
        listed_ns.append(ad / float(sigma))
        cmp_sigma = max(float(sigma), floor_frac * float(pdg))
        floored_ns.append(ad / cmp_sigma)

    def band(ns: list[float], k: float) -> int:
        return sum(1 for x in ns if x <= k)

    n = len(floored_ns)
    return {
        "floor_frac": floor_frac,
        "n": n,
        "within_1sigma_listed": band(listed_ns, 1.0),
        "within_2sigma_listed": band(listed_ns, 2.0),
        "within_3sigma_listed": band(listed_ns, 3.0),
        "within_1sigma_floored": band(floored_ns, 1.0),
        "within_2sigma_floored": band(floored_ns, 2.0),
        "within_3sigma_floored": band(floored_ns, 3.0),
        "max_n_sigma_listed": max(listed_ns) if listed_ns else None,
        "max_n_sigma_floored": max(floored_ns) if floored_ns else None,
    }


def build_sigma_floor_policy_tex() -> str:
    return "\n".join(
        [
            "% Auto-generated by scripts/export_sigma_audit_tex.py — do not edit by hand.",
            "\\begin{table}[ht]",
            "\\centering",
            "\\caption{Dual $\\sigma$ floor policy for apples-to-apples PDG comparisons.",
            " Floors are readout-resolution guards, not claims about experimental precision.}",
            "\\label{tab:sigma-floor-policy}",
            "\\small",
            "\\begin{tabular}{@{}llp{6.8cm}@{}}",
            "\\toprule",
            "Quantity & Combined $n_\\sigma$ denominator & Floor rule \\\\",
            "\\midrule",
            "Mass panel & $\\max(\\sigma_{\\mathrm{ref}}, f M)$ & "
            f"$f=1\\%$ default ({fmt_fraction_pct(0.01)} of $M$); "
            "listed $\\sigma_{\\mathrm{ref}}$ reported separately \\\\",
            "Branching / width & "
            "$\\sqrt{\\sigma_{\\mathrm{pred}}^2+\\sigma_{\\mathrm{ref}}^2}$ & "
            "$\\sigma_{\\mathrm{pred}}\\ge 0.001\\,|\\mathcal{B}_{\\mathrm{pred}}|$ "
            "from Monte Carlo witness propagation \\\\",
            "Half-life envelope & $\\log_{10}|\\mathrm{pred/ref}|$ & "
            "Dressing-aware width ledger ($\\tau_\\mathrm{app}=\\tau_0 f_\\mathrm{out}/f_\\mathrm{weak}$); "
            "no $n_\\sigma$ (width MC $\\sigma$ is not PDG lifetime uncertainty; "
            "Table~\\ref{tab:half-life-dressing}) \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )


def _state_tex(row: dict) -> str:
    key = str(row.get("pdg_key") or "")
    mapping = {
        "J/psi": "$J/\\psi$",
        "psi2S": "$\\psi(2S)$",
        "Upsilon2S": "$\\Upsilon(2S)$",
        "chi_c1": "$\\chi_{c1}$",
        "D0": "$D^0$",
        "B0": "$B^0$",
        "B_plus": "$B^+$",
    }
    if key in mapping:
        return mapping[key]
    name = str(row.get("name", key))
    return name.replace("_", "\\_")


def build_listed_pull_extremes_tex(excited: dict) -> str:
    """Type-A rows where listed PDG σ makes formal n_σ ill-posed (>100σ)."""
    panel_rows = excited.get("pdg_panel_rows") or [
        r for r in excited.get("rows", []) if r.get("pdg_mev") and not r.get("hqiv_only")
    ]
    scored: list[dict] = []
    for row in panel_rows:
        listed = row.get("n_sigma_listed")
        if listed is None or listed <= 100.0:
            continue
        pdg = float(row["pdg_mev"])
        sigma = float(row.get("sigma_mev") or 0)
        sigma_over_m = 100.0 * sigma / pdg if pdg > 0 else 0.0
        scored.append({**row, "sigma_over_m_pct": sigma_over_m})
    scored.sort(key=lambda r: -float(r["n_sigma_listed"]))

    lines = [
        "% Auto-generated by scripts/export_sigma_audit_tex.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{Type~A listed-pull extremes ($n_\\sigma>100$ using raw PDG $\\sigma$). "
        "These six rows have $\\sigma/M\\ll 1\\%$ (often width-derived tags on narrow states); "
        "formal listed $n_\\sigma$ is ill-posed (table shows $\\gg 10^2$; CSV has numeric values). "
        "Scale-free $|\\Delta|/M$ and floored "
        "$\\tilde n_\\sigma$ (Table~\\ref{tab:excited-mass-comparison}) are the honest metrics.}",
        "\\label{tab:listed-pull-extremes}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrr@{}}",
        "\\toprule",
        "State & $|\\Delta|/M$\\,\\% & $\\sigma/M$\\,\\% & $n_\\sigma$ (listed) "
        "& $\\tilde n_\\sigma$ (floored) & Class \\\\",
        "\\midrule",
    ]
    for row in scored:
        name = _state_tex(row)
        listed = float(row["n_sigma_listed"])
        floored = float(row.get("n_sigma_floored") or 0)
        pct = float(row.get("abs_error_pct") or 0)
        sig_pct = float(row["sigma_over_m_pct"])
        listed_s = "$\\gg 10^2$" if listed > 100.0 else f"{listed:.1f}"
        lines.append(
            f"{name} & {pct:.3f} & {sig_pct:.4f} & {listed_s} & {floored:.3f} & Type~A \\\\"
        )
    if not scored:
        lines.append("\\multicolumn{6}{c}{No rows with listed $n_\\sigma>100$.} \\\\")
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def build_sigma_floor_sensitivity_tex(excited: dict) -> str:
    panel_rows = excited.get("pdg_panel_rows") or [
        r for r in excited.get("rows", []) if r.get("pdg_mev") and not r.get("hqiv_only")
    ]
    metrics = [_mass_floor_metrics(panel_rows, f) for f in MASS_FLOORS]
    default = excited

    w1_f = default.get("within_1sigma_floored", "---")
    w1_l = default.get("within_1sigma_listed", "---")
    n_scored = default.get("pdg_scored_count", 85)
    over_100 = int(default.get("listed_pull_over_100sigma_count") or 0)
    caption_tail = (
        f" Default export floor $f=1\\%$ gives ${w1_f}/{n_scored}$ within "
        f"$1\\sigma$ vs.\\ ${w1_l}/{n_scored}$ listed (listed counts are audit-only; "
        f"{over_100} Type-A rows formally $>100\\sigma$; Table~\\ref{{tab:listed-pull-extremes}})."
    )

    lines = [
        "% Auto-generated by scripts/export_sigma_audit_tex.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{Mass-panel $\\sigma$-floor sensitivity on the $85$-state excited spectrum.",
        " ``Listed'' uses published PDG $\\sigma$; ``floored'' replaces "
        "$\\sigma_{\\mathrm{ref}}$ by $\\max(\\sigma_{\\mathrm{ref}}, fM)$ at the stated $f$."
        + caption_tail
        + "}",
        "\\label{tab:sigma-floor-sensitivity}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrrr@{}}",
        "\\toprule",
        "Floor $f$ & \\multicolumn{3}{c}{Listed $n_\\sigma$ counts} & "
        "\\multicolumn{3}{c}{Floored $n_\\sigma$ counts} \\\\",
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
        " & $\\le1\\sigma$ & $\\le2\\sigma$ & $\\le3\\sigma$ & "
        "$\\le1\\sigma$ & $\\le2\\sigma$ & $\\le3\\sigma$ \\\\",
        "\\midrule",
    ]
    for row in metrics:
        f_pct = 100.0 * row["floor_frac"]
        lines.append(
            f"{f_pct:.1f}\\% & "
            f"{row['within_1sigma_listed']}/{row['n']} & "
            f"{row['within_2sigma_listed']}/{row['n']} & "
            f"{row['within_3sigma_listed']}/{row['n']} & "
            f"{row['within_1sigma_floored']}/{row['n']} & "
            f"{row['within_2sigma_floored']}/{row['n']} & "
            f"{row['within_3sigma_floored']}/{row['n']} \\\\"
        )
    lines.extend(
        [
            "\\midrule",
            f"Max listed $n_\\sigma$ & \\multicolumn{{6}}{{r}}{{ill-posed (Type A; Table~\\ref{{tab:listed-pull-extremes}})}} \\\\",
            f"Max floored ($f=1\\%$) & \\multicolumn{{6}}{{r}}{{{fmt_ns(default.get('max_n_sigma_floored'))}}} \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def build_ckm_slot_comparison_tex() -> str:
    lines = [
        "% Auto-generated by scripts/export_sigma_audit_tex.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{CKM \\emph{slot squares} on the discrete carrier vs.\\ PDG $|V_{ij}|$ magnitudes",
        " \\cite{pdg2024}. Slots are upstream probability weights, not a global CKM fit;",
        " branching readouts combine them with open-flavour contacts and normalization.",
        " Pull uses PDG central values and quoted $\\sigma$.}",
        "\\label{tab:ckm-slot-comparison}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrr@{}}",
        "\\toprule",
        "Element & $|V_{ij}|$ slot & PDG $|V_{ij}|$ & $\\sigma$ & "
        "$\\Delta/\\sigma$ & Note \\\\",
        "\\midrule",
    ]
    notes = {
        "V_{us}": "first rung; excellent",
        "V_{cd}": "second rung; compensated by contacts",
        "V_{cb}": "third rung; compensated by contacts",
    }
    for elem, slot, pdg, sigma in CKM_SLOTS:
        pull = (slot - pdg) / sigma
        lines.append(
            f"${elem}$ & {slot:.4f} & {pdg:.4f} & {sigma:.4f} & {pull:+.1f} & {notes[elem]} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def _observation_by_id(observations: dict) -> dict[str, dict]:
    return {
        str(item["id"]): item
        for item in observations.get("branching_comparison_panel") or []
    }


def _daughter_ids_for_item(item: dict) -> list[str]:
    if item.get("daughter_ids"):
        return [str(d) for d in item["daughter_ids"]]
    sets = item.get("daughter_sets") or []
    if not sets:
        return []
    # Use the lightest daughter set as a conservative Q/M proxy for inclusive families.
    def mass_sum(dids: list) -> float:
        return sum(hep.particle_mass_mev(str(d)) for d in dids)

    return [str(d) for d in min(sets, key=mass_sum)]


def _q_over_m(item: dict) -> float | None:
    parent_id = str(item.get("parent_id", ""))
    daughters = _daughter_ids_for_item(item)
    if not parent_id or not daughters:
        return None
    parent_m = hep.particle_mass_mev(parent_id)
    if parent_m <= 0:
        return None
    daughter_m = sum(hep.particle_mass_mev(d) for d in daughters)
    q = parent_m - daughter_m
    return q / parent_m if q > 0 else 0.0


def _n_sigma_ref_only(predicted: float, reference: float, ref_sigma: float | None) -> float | None:
    if ref_sigma is None or ref_sigma <= 0:
        return None
    return abs(predicted - reference) / ref_sigma


def build_branching_diagnostic_tex(
    rows: list[dict],
    observations: dict,
) -> str:
    obs_map = _observation_by_id(observations)
    lines = [
        "% Auto-generated by scripts/export_sigma_audit_tex.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{Curated $17$-channel branching diagnostic with ledger routing, "
        "$Q/M$ kinematic proxy, and dual $n_\\sigma$ conventions.",
        " $n_\\sigma^{\\mathrm{MC}}$ combines Monte Carlo $\\sigma_{\\mathrm{pred}}$ "
        "with PDG $\\sigma_{\\mathrm{ref}}$ (each branching side floored at "
        "$0.001\\,|\\mathcal{B}|$ on the prediction). "
        "$n_\\sigma^{\\mathrm{listed}}$ uses $\\sigma_{\\mathrm{ref}}$ alone.}",
        "\\label{tab:branching-diagnostic}",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{@{}llrrrrrrr@{}}",
        "\\toprule",
        "Channel & Ledger & $Q/M$ & $\\mathcal{B}_{\\mathrm{ref}}$ & "
        "$\\mathcal{B}_{\\mathrm{pred}}$ & $n_\\sigma^{\\mathrm{listed}}$ & "
        "$n_\\sigma^{\\mathrm{MC}}$ & $\\sigma_{\\mathrm{ref}}$ & Note \\\\",
        "\\midrule",
    ]
    for row in rows:
        case_id = str(row.get("case_id", ""))
        item = obs_map.get(case_id, {})
        channel = str(item.get("channel") or case_id.split("_")[1] if "_" in case_id else "")
        ledger = LEDGER_LABELS.get(channel, channel.replace("_", "\\_"))
        qm = _q_over_m(item) if item else None
        label = str(row.get("notes", case_id)).split("; n_")[0].strip()
        if not label.startswith("$"):
            label = label.replace("_", "\\_")
        ref = float(row.get("reference") or 0)
        pred = float(row.get("predicted") or 0)
        ref_s = row.get("reference_sigma")
        n_mc = row.get("n_sigma")
        n_listed = _n_sigma_ref_only(pred, ref, float(ref_s) if ref_s is not None else None)
        note = str(item.get("comparison_note") or "")
        if len(note) > 48:
            note = note[:45] + "..."
        note_tex = _latex_sanitize(note) if note else "---"
        lines.append(
            f"{label} & {ledger} & {fmt_qm(qm)} & {fmt_br(ref)} & {fmt_br(pred)} & "
            f"{fmt_ns(n_listed)} & {fmt_ns(n_mc)} & {fmt_sigma(ref_s)} & "
            f"\\parbox[t]{{3.6cm}}{{{note_tex}}} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def build_branching_pull_histogram_tex(rows: list[dict]) -> str:
    ns = sorted(float(r.get("n_sigma") or 0) for r in rows)
    bins = [(0.0, 0.25), (0.25, 0.5), (0.5, 0.75), (0.75, 1.0), (1.0, 1.5)]
    counts = []
    for lo, hi in bins:
        counts.append(sum(1 for x in ns if lo <= x < hi or (hi == 1.5 and x >= lo)))
    max_count = max(counts) or 1
    bar_w = 0.75
    gap = 0.25
    lines = [
        "% Auto-generated by scripts/export_sigma_audit_tex.py — do not edit by hand.",
        "\\begin{figure}[ht]",
        "\\centering",
        "\\begin{tikzpicture}[x=1.4cm,y=0.55cm]",
        "\\node[anchor=west] at (0, 5.2) {\\small Curated panel $n_\\sigma^{\\mathrm{MC}}$};",
    ]
    for i, ((lo, hi), count) in enumerate(zip(bins, counts)):
        x0 = i * (bar_w + gap)
        height = 4.5 * count / max_count
        label = f"{lo:.2f}--{hi:.2f}" if hi < 1.5 else f"$\\ge${lo:.2f}"
        lines.extend(
            [
                f"\\draw[fill=teal!35,draw=teal!70] ({x0},0) rectangle ({x0 + bar_w},{height:.3f});",
                f"\\node[anchor=north,font=\\scriptsize] at ({x0 + bar_w / 2:.3f},0) {{{label}}};",
                f"\\node[anchor=south,font=\\scriptsize] at ({x0 + bar_w / 2:.3f},{height:.3f}) {{{count}}};",
            ]
        )
    xmax = len(bins) * (bar_w + gap)
    mean_ns = fmt_ns(sum(ns) / len(ns))
    max_ns = fmt_ns(max(ns))
    lines.extend(
        [
            f"\\draw[->] (-0.1,0) -- ({xmax:.2f},0);",
            "\\end{tikzpicture}",
            "\\caption{Monte Carlo $n_\\sigma$ distribution for the curated $17$-channel branching panel."
            + f" Mean {mean_ns}, max {max_ns}."
            + "}",
            "\\label{fig:branching-pull-histogram}",
            "\\end{figure}",
            "",
        ]
    )
    return "\n".join(lines)


def build_branching_pred_ref_scatter_tex(rows: list[dict]) -> str:
    pts: list[tuple[float, float]] = []
    for row in rows:
        ref = row.get("reference")
        pred = row.get("predicted")
        if ref is None or pred is None:
            continue
        pts.append((float(ref), float(pred)))
    if not pts:
        pts = [(0.0, 0.0)]
    xmax = max(max(p[0] for p in pts), max(p[1] for p in pts), 0.05) * 1.1
    scale = 6.0 / xmax

    lines = [
        "% Auto-generated by scripts/export_sigma_audit_tex.py — do not edit by hand.",
        "\\begin{figure}[ht]",
        "\\centering",
        "\\begin{tikzpicture}[x=1cm,y=1cm]",
        f"\\draw[->] (0,0) -- ({xmax * scale + 0.4:.2f},0) "
        f"node[anchor=west] {{$\\mathcal{{B}}_{{\\mathrm{{ref}}}}$}};",
        f"\\draw[->] (0,0) -- (0,{xmax * scale + 0.4:.2f}) "
        f"node[anchor=south,rotate=90] {{$\\mathcal{{B}}_{{\\mathrm{{pred}}}}$}};",
        f"\\draw[dashed,gray] (0,0) -- ({xmax * scale:.2f},{xmax * scale:.2f});",
    ]
    for ref, pred in pts:
        x = ref * scale
        y = pred * scale
        lines.append(f"\\fill[blue!60] ({x:.3f},{y:.3f}) circle (2pt);")
    lines.extend(
        [
            "\\end{tikzpicture}",
            "\\caption{HQIV branching predictions vs.\\ PDG comparison targets on the curated panel.",
            " Dashed line: exact agreement. Points use Monte Carlo--propagated predictions.",
            " Inclusive open-charm families aggregate certified daughter sets (see Table~\\ref{tab:branching-diagnostic}).}",
            "\\label{fig:branching-pred-ref-scatter}",
            "\\end{figure}",
            "",
        ]
    )
    return "\n".join(lines)


def _fmt_halflife_seconds(t: float | None) -> str:
    if t is None or not math.isfinite(t):
        return "---"
    if t >= 1e-3:
        return f"${t * 1e3:.3f}\\,\\mathrm{{ms}}$"
    if t >= 1e-6:
        return f"${t * 1e6:.3f}\\,\\mathrm{{\\mu s}}$"
    if t >= 1e-9:
        return f"${t * 1e9:.3f}\\,\\mathrm{{ns}}$"
    return f"${t:.3e}\\,\\mathrm{{s}}$"


def _species_tex(case_id: str) -> str:
    mapping = {
        "K_plus": "$K^+$",
        "lambda": "$\\Lambda$",
        "mu_plus": "$\\mu^+$",
        "pi_plus": "$\\pi^+$",
    }
    return mapping.get(case_id, case_id.replace("_", "\\_"))


def build_half_life_witness_tex(benchmark: dict) -> str:
    """Dressing-aware half-life panel (log envelopes; no naked n_σ)."""
    rows = [r for r in benchmark.get("rows", []) if r.get("panel") == "half_life"]
    default_env = hep.ExperimentEnvironment()
    beam_env = hep.ExperimentEnvironment(magnetic_field_tesla=0.0, trap_embedding=False)
    f_bottle_trap = lean.trap_weak_width_factor_from_magnetic(
        lean.REPRESENTATIVE_BOTTLE_TRAP_FIELD_TESLA
    )
    sat_ratio = lean.saturated_beam_over_bottle_lifetime_ratio()

    pct_sat = 100.0 * (sat_ratio - 1.0)
    caption_body = (
        "\\caption{Half-life structural witnesses with width-dressing ledger "
        "(same $\\tau_{\\mathrm{app}}=\\tau_0 f_{\\mathrm{out}}/f_{\\mathrm{weak}}$ "
        "as the nucleon $\\beta$ bottle/beam section "
        "\\cite{hqiv-nucleon-binding-paper}). "
        "Predictions use Earth-surface defaults "
        "($T=293\\,\\mathrm{K}$, $B=0$); pass criterion is "
        "$\\log_{10}|\\mathrm{pred}/\\mathrm{ref}|$ envelope only---not $n_\\sigma$. "
        f"Saturated UCN trap envelope $\\tau_\\mathrm{{beam}}/\\tau_\\mathrm{{bottle}}="
        f"{sat_ratio:.4f}$ ({pct_sat:.2f}\\%) is the neutron method reference, not re-fit here."
        + "}"
    )
    lines = [
        "% Auto-generated by scripts/export_sigma_audit_tex.py — do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        caption_body,
        "\\label{tab:half-life-dressing}",
        "\\small",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{@{}lrrrrrrl@{}}",
        "\\toprule",
        "Species & $t_{\\mathrm{ref}}$ & $t_{\\mathrm{pred}}$ & "
        "$\\log_{10}|\\mathrm{pred/ref}|$ & $f_{\\mathrm{weak}}$ & $f_{\\mathrm{out}}$ & "
        "Trap ppm & Pass \\\\",
        "\\midrule",
    ]
    for row in rows:
        if row.get("predicted") is None:
            continue
        case_id = str(row.get("case_id", ""))
        species = case_id
        ref = float(row["reference"])
        pred = float(row["predicted"])
        log10_r = row.get("log10_abs_ratio")
        f_w = row.get("dressing_weak_width_factor")
        f_o = row.get("dressing_outside_support_factor")
        status = str(row.get("status", ""))
        fw_default = float(f_w) if f_w is not None else default_env.weak_width_factor()
        trap_ppm = None
        if fw_default > 0 and f_bottle_trap > 0:
            # Method-consistent bottle shift: τ_app ∝ 1/f_weak (Lean NeutronLifetimeMethod).
            trap_ppm = 1.0e6 * (fw_default / f_bottle_trap - 1.0)
        log_s = f"{float(log10_r):.3f}" if log10_r is not None else "---"
        fw_s = f"{float(f_w):.4f}" if f_w is not None else "---"
        fo_s = f"{float(f_o):.6f}" if f_o is not None else "---"
        ppm_s = f"{trap_ppm:+.0f}" if trap_ppm is not None else "---"
        pass_s = "\\checkmark" if status == "pass" else status
        lines.append(
            f"{_species_tex(case_id)} & {_fmt_halflife_seconds(ref)} & "
            f"{_fmt_halflife_seconds(pred)} & {log_s} & {fw_s} & {fo_s} & {ppm_s} & {pass_s} \\\\"
        )
    lines.extend(
        [
            "\\midrule",
            f"\\multicolumn{{8}}{{p{{0.98\\linewidth}}}}{{\\footnotesize "
            f"Trap ppm: fractional $t_{{1/2}}$ shift from saturated UCN-bottle "
            f"$f_\\mathrm{{weak}}={f_bottle_trap:.4f}$ vs.\\ Earth-surface default "
            f"($f_\\mathrm{{weak}}={default_env.weak_width_factor():.4f}$); "
            f"beam class uses $f_\\mathrm{{weak}}={beam_env.weak_width_factor():.4f}$ "
            f"($\\tau_\\mathrm{{beam}}/\\tau_\\mathrm{{bottle}}\\approx {sat_ratio:.4f}$). "
            f"Width MC propagation yields sub-Attosecond $\\sigma(t_{{1/2}})$ if mis-applied "
            f"as $n_\\sigma$; that artefact is suppressed in exports (no PDG $\\sigma_\\mathrm{{ref}}$ "
            f"on lifetimes).}} \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def export_all(
    *,
    excited_json: Path = DEFAULT_EXCITED_JSON,
    benchmark_json: Path = DEFAULT_BENCHMARK_JSON,
    observations_json: Path = DEFAULT_OBSERVATIONS_JSON,
    out_dir: Path = GENERATED,
) -> None:
    excited = json.loads(excited_json.read_text(encoding="utf-8"))
    benchmark = json.loads(benchmark_json.read_text(encoding="utf-8"))
    observations = json.loads(observations_json.read_text(encoding="utf-8"))
    branching_rows = [
        r
        for r in benchmark.get("rows", [])
        if r.get("panel") == "branching_comparison" and r.get("predicted") is not None
    ]
    out_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        "sigma_floor_policy.tex": build_sigma_floor_policy_tex(),
        "sigma_floor_sensitivity.tex": build_sigma_floor_sensitivity_tex(excited),
        "listed_pull_extremes.tex": build_listed_pull_extremes_tex(excited),
        "ckm_slot_comparison.tex": build_ckm_slot_comparison_tex(),
        "branching_comparison_diagnostic.tex": build_branching_diagnostic_tex(
            branching_rows, observations
        ),
        "branching_pull_histogram.tex": build_branching_pull_histogram_tex(branching_rows),
        "branching_pred_ref_scatter.tex": build_branching_pred_ref_scatter_tex(branching_rows),
        "half_life_witness.tex": build_half_life_witness_tex(benchmark),
    }
    for name, tex in outputs.items():
        path = out_dir / name
        path.write_text(tex, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export σ audit LaTeX for HEP decay paper")
    parser.add_argument("--excited-json", type=Path, default=DEFAULT_EXCITED_JSON)
    parser.add_argument("--benchmark-json", type=Path, default=DEFAULT_BENCHMARK_JSON)
    parser.add_argument("--observations-json", type=Path, default=DEFAULT_OBSERVATIONS_JSON)
    parser.add_argument("--out-dir", type=Path, default=GENERATED)
    args = parser.parse_args()
    export_all(
        excited_json=args.excited_json,
        benchmark_json=args.benchmark_json,
        observations_json=args.observations_json,
        out_dir=args.out_dir,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
